apiVersion: v2
name: kubeteach-core
description: learn kubernetes in kuberenetes
maintainers:
  - name: dergeberl
    url: https://github.com/dergeberl
type: application
version: 0.1.1
appVersion: "v0.1.4-alpha"
