apiVersion: v2
name: kubeteach-exerciseset1
description: learn kubernetes in kuberenetes
type: application
version: 0.1.0
appVersion: "v0.1.4-alpha"
maintainers:
  - name: dergeberl
    url: https://github.com/dergeberl
dependencies:
  - name: kubeteach-core
    repository: 'https://dergeberl.github.io/kubeteach-charts'
    version: "0.1.0"
    alias: kubeteach
